const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:800}});
 const eventName = 'Browser Event '+Date.now();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{console.log('dialog',d.message());await d.accept();});
 await page.goto('http://localhost:8081/');await page.locator('input[name=password]').fill('qa-super');await page.locator('button[type=submit]').click();
 await page.locator('#activitiesList .nav-item').first().waitFor();
 const week=await page.locator('#weekStart').inputValue();
 await page.locator('[data-scope=event]').click();await page.locator('#activityScopeLabel').filter({hasText:'Events'}).waitFor();
 if(await page.locator('#activityWeekSection').isVisible()) throw Error('Events week visible');
 await page.locator('#addActivityBtn').click();await page.locator('#activityNameInput').fill(eventName);
 await page.locator('#eventDate').evaluate(el=>el._flatpickr.setDate('2026-12-01',true));
 await page.locator('#eventDateDisplay').click();
 await page.locator('.flatpickr-calendar.open .flatpickr-day.selected').click();
 const eligible=page.locator('#eventFields fieldset').nth(0),mandatory=page.locator('#eventFields fieldset').nth(1);
 await eligible.getByText('Year 9',{exact:true}).click();await eligible.getByText('Year 10',{exact:true}).click();
 if(await page.locator('#event_manual_student_ids_tags .tag-chip').count()===0)throw Error('Eligible years did not populate students');
 if(await page.locator('.event-roster-summary').count())throw Error('Summary box remains');
 await mandatory.getByText('Year 9',{exact:true}).click();
 await page.locator('#event_excluded_student_ids_add').click();
 await page.locator('#event_excluded_student_ids_search').fill('Legacy Student');
 await page.locator('.student-picker-dropdown:not([hidden]) button').filter({hasText:'Legacy Student'}).first().click();
 await page.locator('#event_included_student_ids_add').click();
 await page.locator('#event_included_student_ids_search').fill('Year Ten');
 await page.locator('.student-picker-dropdown:not([hidden]) button').filter({hasText:'Year Ten'}).click();
 await page.locator('#activityForm .modal-body').evaluate(el=>el.scrollTop=el.scrollHeight);
 await page.screenshot({path:'/tmp/event-desktop.png',animations:'disabled'});
 const footer=await page.locator('#activityForm .modal-footer').boundingBox();if(footer.y+footer.height>800)throw Error('Desktop footer overflow');
 await page.locator('#saveActivityBtn').click();await page.locator('#activityModal').waitFor({state:'hidden'});
 await page.locator('#activityTitle').filter({hasText:eventName}).waitFor();
 const heads=await page.locator('#registerArea th').allTextContents();if(heads.join(',')!=='Student,Mandatory,Attended')throw Error(JSON.stringify(heads));
 const row=page.locator('#registerArea tr').filter({hasText:'Legacy Student'}).first();if(await row.locator('input').first().isChecked())throw Error('Exclusion not optional');
 await row.locator('input').last().check();
 await row.locator('button').click();await page.locator('#eventNoteText').fill('Browser event note');await page.locator('#saveEventNote').click();await page.locator('#eventNoteModal').waitFor({state:'hidden'});
 await row.locator('button').click();if(await page.locator('#eventNoteText').inputValue()!=='Browser event note')throw Error('Note lost');await page.locator('#eventNoteModal .close-modal').first().click();
 await page.locator('#editActivityBtn').click();await page.setViewportSize({width:390,height:640});
 await page.locator('#activityForm .modal-body').evaluate(el=>el.scrollTop=el.scrollHeight);
 const mobile=await page.locator('#activityForm .modal-footer').boundingBox();if(mobile.y+mobile.height>640)throw Error('Mobile footer overflow');
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow');
 await page.screenshot({path:'/tmp/event-mobile.png',animations:'disabled'});
 await eligible.getByText('Year 10',{exact:true}).click();
 if(!(await page.locator('#eventFields [role=status]').textContent()).includes('removed'))throw Error('Eligibility change notice missing');
 if(await page.locator('#eventFields .tag-chip').filter({hasText:'Year Ten'}).count())throw Error('Ineligible inclusion retained');
 await page.locator('#activityModal .close-modal').first().click();
 await page.setViewportSize({width:1280,height:800});
 await page.locator('#navStats').click();await page.locator('#statsArea').waitFor({state:'visible'});
 const download = page.waitForEvent('download');await page.locator('#downloadCsvBtn').click();const file=await download;if(!file.suggestedFilename().startsWith('event_'))throw Error('Export scope label');
 await page.locator('#statsActivitiesTable').getByText(eventName,{exact:true}).click();await page.locator('#activityStatsModal').waitFor({state:'visible'});
 await page.locator('#activityStatsModal .close-modal').first().click();
 if(await page.locator('#openActivityArchive').count())throw Error('Archive link remains');
 await page.locator('[data-scope=normal]').click();await page.locator('#activityWeekSection').waitFor({state:'visible'});
 if(await page.locator('#weekStart').inputValue()!==week)throw Error('Lost normal week');
 await page.locator('[data-scope=normal]').focus();await page.keyboard.press('ArrowRight');await page.locator('[data-scope=event][aria-pressed=true]').waitFor();
 await page.emulateMedia({reducedMotion:'reduce'});const duration=await page.locator('.scope-selection').evaluate(el=>getComputedStyle(el).transitionDuration);if(duration!=='0s')throw Error('Reduced motion '+duration);
 console.log(JSON.stringify({errors,heads,footer,mobile}));if(errors.length)throw Error(errors.join('\n'));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
