const assert = require('node:assert/strict');
const csv = require('../assets/js/student-csv.js');
const fs = require('node:fs');
let records = csv.parse('\uFEFF Name , Year Group , PP , FSM , GENDER , SEN\r\n"O\'NEILL, Alex",y9, T ,F,O,"Special Educational Needs"\r\n"Smith, Jo ""JJ""",10,F,T,F,\r\n');
let rows = csv.mapRows(records, csv.infer(records));
assert.equal(rows[0].name,"Alex O'NEILL");
assert.equal(rows[1].name,'Jo "JJ" Smith');
assert.equal(rows[1].sen_status,'');
assert.equal(rows[0].pp,'T');
assert.equal(rows[0].row_number,2);
records = csv.parse('"DOE, John",y11\n"SMITH, Jane",y10');
rows = csv.mapRows(records,csv.infer(records));
assert.equal(rows[0].name,'John DOE');
assert.equal(rows[0].year_group,'y11');
assert.ok(!Object.hasOwn(rows[0],'sen_status'));
records=csv.parse('DOE,John,y9');
assert.equal(csv.mapRows(records,csv.infer(records))[0].name,'John DOE');
records=csv.parse('DOE John\rSMITH Jane');
assert.equal(csv.mapRows(records,csv.infer(records))[0].year_group,'9');
records=csv.parse('Forename,Surname,Year\n"Jo\nAnne",Smith,10');
assert.equal(csv.mapRows(records,csv.infer(records))[0].name,'Jo\nAnne Smith');
records=csv.parse('NAME,YEAR,PP\nAlex Smith,9');
assert.throws(()=>csv.mapRows(records,csv.infer(records)),/Row 2: missing column/);
assert.throws(()=>csv.parse('"Unclosed'),/unclosed/);
assert.throws(()=>csv.parse('"Name"junk,9'),/quoting/);
records=csv.parse('Custom name,Custom year,Custom SEN\nAlex Smith,9,');
const config=csv.infer(records,true);config.mapping.name=0;config.mapping.year_group=1;config.mapping.sen_status=2;
assert.equal(csv.mapRows(records,config)[0].sen_status,'');
const example=csv.parse(fs.readFileSync('example.csv','utf8'));
assert.equal(csv.mapRows(example,csv.infer(example)).length,3);
console.log('PASS: CSV quoting, BOM, line endings, names, mapping, legacy files, blanks and errors');
